### PR TITLE
Makefile: have a quick way to build the spec file

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by vbatts** [comment]
also, trying out a build of it here https://copr.fedorainfracloud.org/coprs/vbatts/mtree-port/build/798157/

**Comment by archiecobbs** [comment]
Hi @vbatts,

Not sure what the goal of this PR is.

The program is intended to be built using the distribution archive, not the source archive. The distribution archive already contains a `Makefile`, and there is no `autogen.sh`. Distribution archives are available [here](https://github.com/archiecobbs/mtree-port/wiki/Downloads); these are created via `make dist`.

The spec file included in the source is really just an example; each O/S will normally supply their own, e.g. [here is openSUSE's build setup](https://build.opensuse.org/package/show/utilities/mtree).

**Comment by vbatts** [comment]
interesting, I don't see `make dist` working. The thought was to automate a build.

I'm fine having a distro carried spec and build.

**Comment by vbatts** [comment]
oh my gosh how embarrassing. I've totally forgotten about the GNU autoconf tools workflow. You're right. I'll revisit my thoughts here to make a distro rpm for fedora and centos.

**Pull request closed without merging**
